FROM python:3.4-alpine

ENV PYTHONUNBUFFERED 1

RUN apk update && apk add --no-cache \
    py-dnspython \
    py-argparse

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

WORKDIR /app

COPY . .

RUN python setup.py install

ENTRYPOINT ["/usr/local/bin/sublist3r"]
